### ISSUE TITLE
Successfully installed but error while import higher

### ISSUE THREAD

**Issue by AliAbbasi** [facebookresearch/higher#12]
Install either with "pip install ." or with "python setup.py install" in python 3.5.6, with pytorch version 1.3.1. Installed successfully but rise the following error while import higher:

>>> import higher
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\HP\Desktop\higher\higher\__init__.py", line 99
    __all__: list = ["innerloop_ctx"]
           ^
SyntaxError: invalid syntax
>>>

**Comment by AliAbbasi** [comment]
The issue is solved by using python 3.7
