### ISSUE TITLE
How doe one execute an individual higher nn patched module?

### ISSUE THREAD

**Issue by brando90** [facebookresearch/higher#96]
I wanted to execute a module from higher but when I try execute it I get an error:

```
m2(torch.randn([150,1]))
Traceback (most recent call last):
  File "/Users/brando/anaconda3/envs/automl-meta-learning/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-16-3c999f8c42f0>", line 1, in <module>
    m2(torch.randn([150,1]))
  File "/Users/brando/anaconda3/envs/automl-meta-learning/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/brando/higher/higher/patch.py", line 363, in patched_forward
    self.root._refill_params_box(params)
  File "/Users/brando/anaconda3/envs/automl-meta-learning/lib/python3.8/site-packages/torch/nn/modules/module.py", line 771, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'InnerFunctionalLinear' object has no attribute '_refill_params_box'
```

in particular I am looping through the modules from a patched model:

```
    def f(self, fmodel):
        modules = fmodel.named_children()
        out = X
        for (name, m) in modules:
            print(f'{(name, m)')
            out = m(out)
        return out
```

they seem alright when I print them 
```
InnerFunctionalLinear(in_features=1, out_features=60, bias=True)
```
but I can't pass data through them...why?

**Comment by brando90** [comment]
after some work I got that the string it's trying to print is `Out[2]: "'Linear' object has no attribute 'flatten_parameters'"`

**Comment by brando90** [comment]
ok the string it's trying to print is the following: `Out[2]: "'InnerFunctionalLinear' object has no attribute '_refill_params_box'"` for some reason that is an error...figuring out why...

**Comment by brando90** [comment]
Ok so this is what is causing the issue in `patch.py`:
```
        if self.direct_submodule_call:
            # If submodule was called directly, run intialisation that happens
            # at top level call. If *full set of params* is provided here, it 
            # will use those. If not, it will fall back on fast weights.
            # In the future, we should be able to support passing only the 
            # submodule (+ children) weights here, but that's not simple.
            self.root._refill_params_box(params)
```

I take based on what fast weights might mean that those are the weights after a few updates of MAML for example
 ```
fasta_weights = Adaptation(meta_weight)
```
however, for some reason the `InnerFunctionalLinear ` does not have the function `_refill_params_box`. I want to use the fast weights (after adapting MAML on the current support set). I see from inspecting in my debugger that the `params=None` which makes sense since I want to use the adapted weights. 

Currently it seems it might be fixed for my use case if I just force set `self.direct_submodule_call = False` despite me calling it directly when getting the child modules. Seems terribly hacky but Idk how else to go around it for now:
```
   def f(self, fmodel):
        modules = fmodel.named_children()
        out = X
        for (name, m) in modules:
            print(f'{(name, m)')
            m.direct_submodule_call = False
            out = m(out)
        return out
```

**Comment by brando90** [comment]
darn it doesn't let me do it...
```
  File "/Users/brando/automl-meta-learning/automl-proj/meta_learning/meta_learners/maml_meta_learner.py", line 290, in get_l2_distances_per_layer
    m2.direct_submodule_call = False
  File "/Users/brando/higher/higher/patch.py", line 318, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute
```

**Comment by brando90** [comment]
it seems I can force it do it (perhaps? I am not 100% if it's working as I intended) if I pass the original unadapted model as an argument and then I load the state dict using the adapted weights (which I am taking higher refers to as fast weights in the current/old documentation depending when you read this).

```
    def f(self, mdl1, mdl2, X,):
        modules = zip(mdl1.named_children(), mdl2.named_children())
        out1 = X
        out2 = X
        for (name1, m1), (name2, m2) in modules:
            print(f'{(name1, m1), (name2, m2)}')
            out1 = m1(out1)
            # m2.direct_submodule_call = False
            m1.load_state_dict(m2.state_dict())
            out2 = m1(out2)
```
is there a way to solve this in a less hacky way?

**Comment by brando90** [comment]
> it seems I can force it do it (perhaps? I am not 100% if it's working as I intended)

the reason I am unsure if it's working is that when I print the weights they seem too similar...though I do get a few "falses" when I compare them:

```
out1
Out[5]: 
tensor([[-0.1519, -0.6428,  1.3292,  ..., -0.2724, -0.6826,  0.0502],
        [-1.8627, -0.6212,  2.6815,  ..., -0.2642, -0.6025, -1.4473],
        [-6.3190, -0.5651,  6.2037,  ..., -0.2429, -0.3940, -5.3476],
        ...,
        [-6.4152, -0.5639,  6.2798,  ..., -0.2424, -0.3895, -5.4319],
        [-1.4413, -0.6265,  2.3484,  ..., -0.2662, -0.6223, -1.0785],
        [ 0.4883, -0.6508,  0.8232,  ..., -0.2755, -0.7125,  0.6105]],
       grad_fn=<AddmmBackward>)
out2
Out[6]: 
tensor([[-0.1519, -0.5300,  1.3292,  ...,  0.2442, -0.7063,  0.0502],
        [-1.8628, -0.3043,  2.6815,  ...,  1.1868, -0.6691, -1.4473],
        [-6.3190,  0.2833,  6.2037,  ...,  3.6421, -0.5722, -5.3476],
        ...,
        [-6.4152,  0.2960,  6.2798,  ...,  3.6951, -0.5701, -5.4319],
        [-1.4413, -0.3599,  2.3484,  ...,  0.9547, -0.6782, -1.0785],
        [ 0.4883, -0.6144,  0.8232,  ..., -0.1085, -0.7202,  0.6105]],
       grad_fn=<AddmmBackward>)
```

see

```
(out1 == out2).any()
Out[3]: tensor(True)
(out1 == out2).all()
Out[4]: tensor(False)
```

which tests if any is true or if all are true (if MAML is working I would have expected for both to be false since it's really hard for two "floats/real" numbers to be EXACTLY the same after a non zero operation...

**Comment by brando90** [comment]
perhaps it's alright? The L2 distances seem sensible...?

```
(m1.weight - m2.weight).sum()
Out[2]: tensor(-2.6643, grad_fn=<SumBackward0>)
(out1 - out2).sum()
Out[3]: tensor(-1255.9127, grad_fn=<SumBackward0>)
(out1 - out2).norm(2)
Out[4]: tensor(70.9542, grad_fn=<NormBackward0>)
```

**Comment by brando90** [comment]
Ok to be sure I did another test:
```
            print(f'{(name1, m1), (name2, m2)}')
            print(m1.weight.sum())
            out1 = m1(out1)
            m = copy.deepcopy(m1)
            m.load_state_dict(m2.state_dict())
            out2 = m(out2)
            print(m1.weight.sum())
```
so this makes sure that although I am loading `m1` with the weights of `m2`, it doesn't accidentally overwrite the weights of `m1` to be the weights of `m2` **permanently**, in case it is using pointers/references inside of the python/pytorch implementation. i.e. `m` is really meant to be `m2` but I don't want to remove `m2`'s reference since I eventually need its weights to create the copy of `m2` that **IS** callable. Calling `m2` doesn't work for some reason.

**Comment by brando90** [comment]
related:

- https://stackoverflow.com/questions/27396339/attributeerror-cant-set-attribute/27627094?noredirect=1#comment116758917_27627094
- https://softwareengineering.stackexchange.com/questions/371540/should-a-python-property-decorator-be-used-without-a-setter-or-deleter

**Comment by egrefen** [comment]
Hello. I need a self-contained and minimal working example, please. Preferably with what the intended output was, and the error/traceback was.
